version: '3.9'

services:
  whoami:
    restart: unless-stopped
    image: traefik/whoami
    labels:
      - 'traefik.enable=true'
    networks:
      - default
      - traefik

networks:
  traefik:
    name: traefik
    external: true
