version: '3.9'

services:
  traefik:
    image: traefik:2.7
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: traefik.yml
        target: /etc/traefik/traefik.yml
        read_only: true
    network_mode: host
    restart: unless-stopped
